export const ACTIONTYPES = {
  TOOGLETABLETSIDEBAR: "TOOGLETABLETSIDEBAR",
  TOOGLETABLETSIDEBAR_SUCCESS: "TOOGLETABLETSIDEBAR_SUCCESS",
  TOOGLEDESKTOPSIDEBAR: "TOOGLEDESKTOPSIDEBAR",
  TOOGLEDESKTOPSIDEBAR_SUCCESS: "TOOGLEDESKTOPSIDEBAR_SUCCESS",
};
