export const ACTIONTYPES = {
  TOOGLETABLETSIDEBAR: "TOOGLETABLETSIDEBAR",
  TOOGLETABLETSIDEBAR_SUCCESS: "TOOGLETABLETSIDEBAR_SUCCESS",
  TOOGLEDESKTOPSIDEBAR: "TOOGLEDESKTOPSIDEBAR",
  TOOGLEDESKTOPSIDEBAR_SUCCESS: "TOOGLEDESKTOPSIDEBAR_SUCCESS",
  TOOGLESLIDE: "TOOGLESLIDE",
  //// tooltip hovered effect
  APPLEHOVER: "APPLEHOVER",
  ANDROIDHOVER: "ANDROIDHOVER",
  WEBHOVER: "WEBHOVER",
  UNITYHOVER: "UNITYHOVER",
  FLUTTERHOVER: "FLUTTERHOVER",
};
